### ISSUE TITLE
Implement setWhitelist Function for ERC404 Cairo

### ISSUE THREAD

**Issue by marciob** [marciob/ERC404-Cairo#4]
This issue involves implementing the setWhitelist function for the ERC404 Cairo contract. This function is used to manage addresses that are exempt from certain token minting/burning rules for gas efficiency.

Ensure the function:
- Can only be called by the contract owner.
- Properly updates the whitelist status of a given address.

Adapt the logic from the Solidity version to Cairo, focusing on proper access control and state management.

Reference: [ERC404 Solidity Implementation](https://github.com/0xacme/ERC404/)

**Comment by Falco90** [comment]
I can take it!
